### ISSUE TITLE
Using NLTK to find related words doesn't work if download directory for nltk_data is changed.

### ISSUE THREAD

**Issue by 53R3n17Y-serenity** [mike-fabian/ibus-typing-booster#337]
Everything works per this instruction, [Using NLTK to find related words](https://mike-fabian.github.io/ibus-typing-booster/docs/user/#9)
But if I change Download Directory in a [NLTK Downloader](https://mike-fabian.github.io/ibus-typing-booster/images/user-docs/nltk-wordnet-corpus-download.png), from _my_ default `/home/me/nltk_data` to `/home/me/testboost/nltk_data`, it downloads like before but `lookup_related` no longer works, even after log out. 
What am I missing?
TIA

**Comment by mike-fabian** [comment]
It should work if you set this in your environment:

```
export NLTK_DATA='/home/me/testboost/nltk_data'
```

**Comment by mike-fabian** [comment]
If I look a the code in `/usr/lib/python3.10/site-packages/nltk/data.py` in Fedora 36, I see:

```python
######################################################################
# Search Path
######################################################################

path = []
"""A list of directories where the NLTK data package might reside.
   These directories will be checked in order when looking for a
   resource in the data package.  Note that this allows users to
   substitute in their own versions of resources, if they have them
   (e.g., in their home directory under ~/nltk_data)."""

# User-specified locations:
_paths_from_env = os.environ.get("NLTK_DATA", str("")).split(os.pathsep)
path += [d for d in _paths_from_env if d]
if "APPENGINE_RUNTIME" not in os.environ and os.path.expanduser("~/") != "~/":
    path.append(os.path.expanduser(str("~/nltk_data")))

if sys.platform.startswith("win"):
    # Common locations on Windows:
    path += [
        os.path.join(sys.prefix, str("nltk_data")),
        os.path.join(sys.prefix, str("share"), str("nltk_data")),
        os.path.join(sys.prefix, str("lib"), str("nltk_data")),
        os.path.join(os.environ.get(str("APPDATA"), str("C:\\")), str("nltk_data")),
        str(r"C:\nltk_data"),
        str(r"D:\nltk_data"),
        str(r"E:\nltk_data"),
    ]
else:
    # Common locations on UNIX & OS X:
    path += [
        os.path.join(sys.prefix, str("nltk_data")),
        os.path.join(sys.prefix, str("share"), str("nltk_data")),
        os.path.join(sys.prefix, str("lib"), str("nltk_data")),
        str("/usr/share/nltk_data"),
        str("/usr/local/share/nltk_data"),
        str("/usr/lib/nltk_data"),
        str("/usr/local/lib/nltk_data"),
    ]


######################################################################
```

**Comment by mike-fabian** [comment]
So setting `NLTK_DATA` should help.

**Comment by 53R3n17Y-serenity** [comment]
> It should work if you set this in your environment:
> 
> ```
> export NLTK_DATA='/home/me/testboost/nltk_data'
> ```
I appreciate your response, Mike. 
Doesn't work. _This is beyond my comprehension, so I'm learning as I go._ 
I set
```
export NLTK_DATA='/home/me/testboost/nltk_data'
echo $NLTK_DATA
/home/me/testboost/nltk_data
```

I added the line `export NLTK_DATA='/home/me/testboost/nltk_data'` to `.bashrc` so it's set permanently. Verified with `echo $NLTK_DATA` after log out.
I try to "find related" but it still doesn't work. _(With logging out, in two different programs (FF, gedit) where default  `/home/me/nltk_data` does work._ 

I'm on Ubuntu 20.04, searched for the code _(which I don't understand)_, found it in 
`/usr/lib/python3/dist-packages/nltk/data.py`. In VSCode I "compared with selected" the same "Search Path" selection. The only difference it showed is single `'`vs double`"` quotes in the code. Which probably has no effect in my situation.

```py
######################################################################
# Search Path
######################################################################

path = []
"""A list of directories where the NLTK data package might reside.
   These directories will be checked in order when looking for a
   resource in the data package.  Note that this allows users to
   substitute in their own versions of resources, if they have them
   (e.g., in their home directory under ~/nltk_data)."""

# User-specified locations:
_paths_from_env = os.environ.get('NLTK_DATA', str('')).split(os.pathsep)
path += [d for d in _paths_from_env if d]
if 'APPENGINE_RUNTIME' not in os.environ and os.path.expanduser('~/') != '~/':
    path.append(os.path.expanduser(str('~/nltk_data')))

if sys.platform.startswith('win'):
    # Common locations on Windows:
    path += [
        os.path.join(sys.prefix, str('nltk_data')),
        os.path.join(sys.prefix, str('share'), str('nltk_data')),
        os.path.join(sys.prefix, str('lib'), str('nltk_data')),
        os.path.join(os.environ.get(str('APPDATA'), str('C:\\')), str('nltk_data')),
        str(r'C:\nltk_data'),
        str(r'D:\nltk_data'),
        str(r'E:\nltk_data'),
    ]
else:
    # Common locations on UNIX & OS X:
    path += [
        os.path.join(sys.prefix, str('nltk_data')),
        os.path.join(sys.prefix, str('share'), str('nltk_data')),
        os.path.join(sys.prefix, str('lib'), str('nltk_data')),
        str('/usr/share/nltk_data'),
        str('/usr/local/share/nltk_data'),
        str('/usr/lib/nltk_data'),
        str('/usr/local/lib/nltk_data'),
    ]


######################################################################
```

**Comment by mike-fabian** [comment]
Works for me. Can you try wether the same as I did here works for you?::

I created a `testboost` directory and moved the data there:

```
mkdir ~/testboost/
mv ~/nltk_data  ~/testboost/
```

Then go to `/usr/share/ibus-typing-booster/engine` and try to run the doctests for nltk:

```
mfabian@taka:/usr/share/ibus-typing-booster/engine
$ python3 itb_nltk.py 
```

This prints some errors now:

```
mfabian@taka:/usr/share/ibus-typing-booster/engine (release-candidate-2.17.1 $)
$ python3 itb_nltk.py
LookupError:
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/home/mfabian/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'  
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

```

Now try again with the environment variable set:

```
mfabian@taka:/usr/share/ibus-typing-booster/engine (release-candidate-2.17.1 $)
$ NLTK_DATA="/home/mfabian/testboost/nltk_data" python3 itb_nltk.py 
         14469 function calls (14229 primitive calls) in 0.013 seconds
         ... some more performance data but no errors ...
```

Tilde expansion doesn’t seem to work, trying it like this

```
mfabian@taka:/usr/share/ibus-typing-booster/engine (release-candidate-2.17.1 $)
$ NLTK_DATA="~/testboost/nltk_data" python3 itb_nltk.py 
```

produces the errors again.

**Comment by 53R3n17Y-serenity** [comment]
@mike-fabian 
I try to follow you from scratch. 
Deleted `testboot` directory, commented out `.bashrc` line `#export NLTK_DATA='/home/me/testboost/nltk_data'`, reboot, verify export variable is not set with `echo $NLTK_DATA`, redownload `nltk_data` per original instructions. Then follow your above instructions. 

Follow #1— **variable not set**
Errors.

<Details>

```bash
me@PC:~$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.download()
showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml
True
>>> 

me@PC:$ mkdir ~/testboost/
me@PC:$ mv ~/nltk_data  ~/testboost/
me@PC:~$ cd /usr/share/ibus-typing-booster/engine
me@PC:/usr/share/ibus-typing-booster/engine$ python3 itb_nltk.py 
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/home/me/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 86, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
  File "/usr/lib/python3/dist-packages/nltk/data.py", line 701, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet.zip/wordnet/

  Searched in:
    - '/home/me/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "itb_nltk.py", line 157, in _init
    wordnet.synsets('car')
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 123, in __getattr__
    self.__load()
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 88, in __load
    raise e
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 83, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
  File "/usr/lib/python3/dist-packages/nltk/data.py", line 701, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/home/me/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "itb_nltk.py", line 178, in <module>
    __module_init = __ModuleInitializer()
  File "itb_nltk.py", line 172, in __init__
    _init()
  File "itb_nltk.py", line 160, in _init
    raise LookupError from error
LookupError
```
</Details>

Follow #2—**variable set**
No errors. Test "find related", still doesn't work. 

<Details>

```bash
me@PC:~$ export NLTK_DATA='/home/me/testboost/nltk_data'
me@PC:~$ echo $NLTK_DATA
/home/me/testboost/nltk_data
me@PC:~$ cd /usr/share/ibus-typing-booster/engine
me@PC:/usr/share/ibus-typing-booster/engine$ python3 itb_nltk.py 
         15642 function calls (15374 primitive calls) in 0.025 seconds

   Ordered by: cumulative time
   List reduced from 412 to 8 due to restriction <'nltk'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        3    0.000    0.000    0.014    0.005 itb_nltk.py:67(hyponyms)
      111    0.000    0.000    0.001    0.000 itb_nltk.py:86(<genexpr>)
        3    0.000    0.000    0.000    0.000 itb_nltk.py:96(hypernyms)
       12    0.000    0.000    0.000    0.000 itb_nltk.py:113(<genexpr>)
        3    0.000    0.000    0.000    0.000 itb_nltk.py:41(synonyms)
        1    0.000    0.000    0.000    0.000 itb_nltk.py:123(related)
        1    0.000    0.000    0.000    0.000 itb_nltk.py:150(_init)
       18    0.000    0.000    0.000    0.000 itb_nltk.py:58(<genexpr>)


         15642 function calls (15374 primitive calls) in 0.025 seconds

   Ordered by: cumulative time
   List reduced from 412 to 20 due to restriction <'wordnet'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       69    0.000    0.000    0.014    0.000 wordnet.py:1374(synset_from_pos_and_offset)
       10    0.000    0.000    0.013    0.001 wordnet.py:1568(synsets)
       10    0.000    0.000    0.013    0.001 wordnet.py:1582(<listcomp>)
       27    0.000    0.000    0.013    0.000 wordnet.py:1362(_data_file)
       12    0.000    0.000    0.001    0.000 wordnet.py:1056(_related)
        7    0.000    0.000    0.001    0.000 wordnet.py:1061(<listcomp>)
        9    0.000    0.000    0.001    0.000 wordnet.py:144(hyponyms)
       27    0.001    0.000    0.001    0.000 wordnet.py:1396(_synset_from_pos_and_line)
       40    0.000    0.000    0.000    0.000 wordnet.py:1873(_morphy)
        3    0.000    0.000    0.000    0.000 wordnet.py:132(hypernyms)
      586    0.000    0.000    0.000    0.000 wordnet.py:1415(_next_token)
       40    0.000    0.000    0.000    0.000 wordnet.py:1884(apply_rules)
       40    0.000    0.000    0.000    0.000 wordnet.py:1885(<listcomp>)
       27    0.000    0.000    0.000    0.000 wordnet.py:420(__init__)
       40    0.000    0.000    0.000    0.000 wordnet.py:1892(filter_forms)
       60    0.000    0.000    0.000    0.000 wordnet.py:279(__init__)
      140    0.000    0.000    0.000    0.000 wordnet.py:213(__lt__)
      117    0.000    0.000    0.000    0.000 wordnet.py:300(name)
       49    0.000    0.000    0.000    0.000 wordnet.py:482(lemmas)
        3    0.000    0.000    0.000    0.000 wordnet.py:469(lemma_names)
```

</Details>

Follow #3—with tilde expression, errors (log not included)

---

Just taking a _wild guess_ that maybe in Ubuntu 20.04 I need to set "environment variable" differently. Not in general how `export` works, but in my particular situation with "nltk_data" and Typing Booster. 
Because with default location `Mod5+F12` serves/fetches related, while with alternate location "suggestions window" blinks/reloads as before, as if trying to serve/fetch but doesn't, remaining at previous suggestions without populating related ones. 

>[Session-wide environment variables - Community Help Wiki](https://help.ubuntu.com/community/EnvironmentVariables#Session-wide_environment_variables "Session-wide environment variables - Community Help Wiki")
> Shell config files such as ~/.bashrc, ~/.bash_profile, and ~/.bash_login are often suggested for setting environment variables. While this may work on Bash shells for programs started from the shell, **variables set in those files are not available by default to programs started from the graphical environment in a desktop session**.

**Comment by mike-fabian** [comment]
Maybe '.bashrc' is not read early enough when the session starts but '.profile' is.

**Comment by mike-fabian** [comment]
Reopened to remind me to check it.

**Comment by mike-fabian** [comment]
> During installation, there were some warnings and errors in bash shell. Maybe something during installation leads to "incomplete" installation.
> 
> I include my bash installation process for you, if it's of any use for you. [ubuntu-22.04-typing-booster2.19.2-git.log](https://github.com/mike-fabian/ibus-typing-booster/files/9790880/ubuntu-22.04-typing-booster2.19.2-git.log)

Your log file contains:

```
Making all in po
make[1]: Entering directory '/home/test/ibus-typing-booster/po'
test ! -f ./ibus-typing-booster.pot || \
  test -z "ar.gmo bn.gmo ca.gmo cs.gmo de.gmo es.gmo fa.gmo fr.gmo he.gmo hu.gmo it.gmo ja.gmo ka.gmo nl.gmo or.gmo pl.gmo pt.gmo pt_BR.gmo si.gmo sv.gmo sw.gmo tr.gmo uk.gmo zh_CN.gmo zh_TW.gmo" || make ar.gmo bn.gmo ca.gmo cs.gmo de.gmo es.gmo fa.gmo fr.gmo he.gmo hu.gmo it.gmo ja.gmo ka.gmo nl.gmo or.gmo pl.gmo pt.gmo pt_BR.gmo si.gmo sv.gmo sw.gmo tr.gmo uk.gmo zh_CN.gmo zh_TW.gmo
make[2]: Entering directory '/home/test/ibus-typing-booster/po'
rm -f ar.gmo && : -c --statistics -o ar.gmo ar.po
mv: cannot stat 't-ar.gmo': No such file or directory
make[2]: *** [Makefile:142: ar.gmo] Error 1
make[2]: Leaving directory '/home/test/ibus-typing-booster/po'
make[1]: *** [Makefile:172: stamp-po] Error 2
make[1]: Leaving directory '/home/test/ibus-typing-booster/po'
make: *** [Makefile:525: all-recursive] Error 1
```

On my Fedora 37 this looks like:

```
Making all in po
make[1]: Entering directory '/local/mfabian/src/ibus-typing-booster/po'
test ! -f ./ibus-typing-booster.pot || \
  test -z "ar.gmo bn.gmo ca.gmo cs.gmo de.gmo es.gmo fa.gmo fr.gmo he.gmo hu.gmo it.gmo ja.gmo ka.gmo nl.gmo or.gmo pl.gmo pt.gmo pt_BR.gmo si.gmo sv.gmo sw.gmo tr.gmo uk.gmo zh_CN.gmo zh_TW.gmo" || make ar.gmo bn.gmo ca.gmo cs.gmo de.gmo es.gmo fa.gmo fr.gmo he.gmo hu.gmo it.gmo ja.gmo ka.gmo nl.gmo or.gmo pl.gmo pt.gmo pt_BR.gmo si.gmo sv.gmo sw.gmo tr.gmo uk.gmo zh_CN.gmo zh_TW.gmo
make[2]: Entering directory '/local/mfabian/src/ibus-typing-booster/po'
rm -f ar.gmo && /usr/bin/msgfmt -c --statistics -o ar.gmo ar.po
ar.po:8: warning: header field 'Project-Id-Version' still has the initial default value
226 translated messages.
```

Somehow I don’t see `/usr/bin/msgfmt` in your log. Is this not available?

On Fedora this is part of the gettext package:

```
$ rpm -qf /usr/bin/msgfmt
gettext-0.21.1-1.fc37.x86_64
```
