### ISSUE TITLE
`make check` fails on FreeBSD since 2.5.0

### ISSUE THREAD

**Issue by thierry-FreeBSD** [mike-fabian/ibus-typing-booster#46]
Hello,
Issue #38 (Korean) is still open, but `make check`fails on FreeBSD with 2.5.0 and 2.5.1 with a different error:
```
======================================================================
ERROR: test_accent_insensitive_matching_french_dictionary (test_itb.ItbTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/textproc/ibus-typing-booster/work/ibus-typing-booster-2.5.1/tests/test_itb.py", line 50, in setUp
    self.set_default_settings()
  File "/usr/ports/textproc/ibus-typing-booster/work/ibus-typing-booster-2.5.1/tests/test_itb.py", line 155, in set_default_settings
    'toggle_off_the_record': ['Mod5+F9'],
  File "../engine/hunspell_table.py", line 1265, in set_keybindings
    self._init_properties()
  File "../engine/hunspell_table.py", line 1627, in _init_properties
    self.dictionary_menu, current_mode=0)
  File "../engine/hunspell_table.py", line 1367, in _init_or_update_property_menu_dictionary
    sub_properties, current_mode=current_mode)
  File "../engine/hunspell_table.py", line 1469, in _init_or_update_sub_properties_dictionary
    self._prop_dict[mode].set_label(
KeyError: 'Dictionary.0'

======================================================================
```
Note: py-hunspell is 0.5.5 (Python 3.6).
A solution for this problem is given at https://stackoverflow.com/questions/23297569/python-key-error-0-cant-find-dict-error-in-code

**Comment by mike-fabian** [comment]
Fixed in https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.5.2
