### ISSUE TITLE
Feeble locale interpretation

### ISSUE THREAD

**Issue by altblue** [mike-fabian/ibus-typing-booster#97]
`ibus-typing-booster` v2.8.2 _setup_ crashes when `LC_MESSAGES` is set to only the `language` part of any `[language[_territory][.codeset][@modifier]]` definition:

```
$ tail -1 /usr/share/ibus-typing-booster/setup/version.py
    return "2.8.2"

$ LC_MESSAGES=C python3 /usr/share/ibus-typing-booster/setup/main.py
/usr/share/ibus-typing-booster/setup/main.py:150: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  'ibus-setup-typing-booster', 'Typing Booster Preferences')
Traceback (most recent call last):
  File "/usr/share/ibus-typing-booster/setup/main.py", line 4683, in <module>
    SETUP_UI = SetupUI()
  File "/usr/share/ibus-typing-booster/setup/main.py", line 789, in __init__
    self._fill_dictionaries_listbox()
  File "/usr/share/ibus-typing-booster/setup/main.py", line 1820, in _fill_dictionaries_listbox
    missing_dictionary) = self._fill_dictionaries_listbox_row(name)
  File "/usr/share/ibus-typing-booster/setup/main.py", line 1724, in _fill_dictionaries_listbox_row
    if itb_util.is_right_to_left_messages():
  File "/usr/share/ibus-typing-booster/setup/../engine/itb_util.py", line 2636, in is_right_to_left_messages
    lang = lc_messages_locale.split('_')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by mike-fabian** [comment]
The fix is included in the 2.8.3 release:

https://github.com/mike-fabian/ibus-typing-booster/releases/tag/2.8.3
